### ISSUE TITLE
Home - No redirection to the "gitlab token generate" page.

### ISSUE THREAD

**Issue by Adrixop95** [GitLab-Helper/gitlab-helper-frontend#6]
Clicking the "How to generate gitlab token?" Button does not redirect the user to the gitlab website.
https://docs.gitlab.com/ee/user/profile/personal_access_tokens.html

![Adnotacja 2020-09-05 151014](https://user-images.githubusercontent.com/6369508/92305722-1bd9b800-ef8a-11ea-8e4b-679ec84436be.png)

**Comment by Trixie94** [comment]
Redirect fixed. They open in new tab with given link.
